# Generated by Django 5.2 on 2025-04-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEPI', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('validade', models.DateField()),
                ('quantidade_disponivel', models.IntegerField()),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=100)),
                ('colaborador', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('condquipamento', models.CharField(max_length=100)),
                ('observacao', models.CharField(max_length=100)),
                ('datadevolucao', models.DateField()),
                ('dataemprestimo', models.DateField()),
                ('dataprevistadadevolucao', models.DateField()),
            ],
        ),
    ]
