# Generated by Django 5.1.7 on 2025-04-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_alter_registrar_datadevolucao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrar',
            old_name='condquipamento',
            new_name='condicao_quipamento',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='datadevolucao',
            new_name='data_devolucao',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='dataemprestimo',
            new_name='data_emprestimo',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='dataprevistadadevolucao',
            new_name='data_prevista_da_devolucao',
        ),
    ]
