# Generated by Django 5.1.6 on 2025-04-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_rename_condquipamento_registrar_condicao_quipamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrar',
            old_name='condicao_quipamento',
            new_name='condicao_equipamento',
        ),
    ]
