# Generated by Django 5.2 on 2025-04-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_rename_condicao_quipamento_registrar_condicao_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app_home.colaborador'),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app_home.epi'),
        ),
    ]
