# Generated by Django 5.2 on 2025-04-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0006_alter_registrar_colaborador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='epi',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='condicao_equipamento',
            field=models.CharField(choices=[('bom', 'Bom Estado'), ('usado_bom', 'Usado'), ('manutencao', 'Em Manutenção'), ('quebrado', 'Quebrado/Danificado'), ('indisponivel', 'Indisponível'), ('vencido', 'Vencido'), ('aguardando_substituicao', 'Aguardando Substituição'), ('contaminado', 'Contaminado'), ('descartabilidade', 'Em Descartabilidade')], max_length=100),
        ),
    ]
