# Generated by Django 6.1.1 on 2026-10-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0007_aviso_alter_epi_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(max_length=50),
        ),
    ]
